"""Pack the approved Crayon home artwork into a bounded indexed bitmap."""

import pathlib
import random

from PIL import Image, ImageDraw


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "skins" / "crayon" / "home-neutral-source.png"
SELECTED_SOURCES = tuple(
    ROOT / "assets" / "skins" / "crayon" / f"home-selected-{name}.png"
    for name in ("status", "files", "devices", "workbench", "audit", "system")
)
OUTPUT = (ROOT / "services" / "appearance" / "include" / "picopen" /
          "crayon_screen_asset.h")
WIDTH = 320
HEIGHT = 320
COLORS = 64
FOCUS_WIDTH = 146
FOCUS_HEIGHT = 88
FOCUS_X = (3, 171, 3, 171, 3, 171)
FOCUS_Y = (52, 52, 125, 125, 200, 200)


def focus_mask(seed):
    randomizer = random.Random(seed)
    mask = Image.new("L", (FOCUS_WIDTH, FOCUS_HEIGHT), 255)
    draw = ImageDraw.Draw(mask)
    # Loose wax strokes: different lengths, slopes, curvature, and pressure.
    # They intentionally do not form or touch a rectangular perimeter.
    for stroke in range(23):
        center_y = 8 + stroke * 70 / 22 + randomizer.uniform(-5.0, 5.0)
        start = randomizer.randint(3, 28)
        end = FOCUS_WIDTH - randomizer.randint(4, 25)
        slope = randomizer.uniform(-0.13, 0.13)
        bend = randomizer.uniform(-6.0, 6.0)
        points = []
        for x in range(start, end + 1, randomizer.choice((5, 6, 7))):
            progress = (x - start) / max(1, end - start)
            curve = bend * (4.0 * progress * (1.0 - progress))
            jitter = randomizer.uniform(-2.8, 2.8)
            y = center_y + slope * (x - start) + curve + jitter
            points.append((x, int(y)))
        if len(points) < 2:
            continue
        color = randomizer.randrange(5)
        for segment in range(len(points) - 1):
            # Pressure changes along a single stroke instead of a uniform line.
            width = randomizer.choice((1, 2, 2, 3, 3, 4))
            draw.line((points[segment], points[segment + 1]),
                      fill=color, width=width)

    # A few energetic edge marks make every selected item visibly different.
    for _ in range(7):
        x = randomizer.choice((randomizer.randint(1, 18),
                               randomizer.randint(126, 144)))
        y = randomizer.randint(7, 78)
        draw.line((x, y, x + randomizer.randint(-10, 10),
                   y + randomizer.randint(-9, 9)),
                  fill=randomizer.randrange(5), width=randomizer.choice((1, 2)))

    # Small holes reproduce broken wax coverage and visible paper tooth.
    pixels = mask.load()
    for y in range(FOCUS_HEIGHT):
        for x in range(FOCUS_WIDTH):
            if pixels[x, y] != 255 and randomizer.random() < 0.14:
                pixels[x, y] = 255
    return mask.tobytes()


def selected_crops(base_palette):
    crops = []
    for source_path, origin_x, origin_y in zip(SELECTED_SOURCES, FOCUS_X, FOCUS_Y):
        selected = Image.open(source_path).convert("RGB").resize(
            (WIDTH, HEIGHT), Image.Resampling.LANCZOS)
        crop = selected.crop((origin_x, origin_y, origin_x + FOCUS_WIDTH,
                              origin_y + FOCUS_HEIGHT))
        crops.append(crop.quantize(palette=base_palette,
                                   dither=Image.Dither.FLOYDSTEINBERG).tobytes())
    return crops


def main():
    source = Image.open(SOURCE).convert("RGB")
    resized = source.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    indexed = resized.quantize(colors=COLORS, method=Image.Quantize.MEDIANCUT,
                               dither=Image.Dither.FLOYDSTEINBERG)
    palette_data = indexed.getpalette()[:COLORS * 3]
    palette = [
        (palette_data[index] << 16) |
        (palette_data[index + 1] << 8) |
        palette_data[index + 2]
        for index in range(0, len(palette_data), 3)
    ]
    pixels = indexed.tobytes()
    focus_masks = [focus_mask(1701 + index * 97) for index in range(6)]
    selected = selected_crops(indexed)
    lines = [
        "// Generated by tools/generate_crayon_screen.py from approved artwork.",
        "#ifndef PICOPEN_CRAYON_SCREEN_ASSET_H",
        "#define PICOPEN_CRAYON_SCREEN_ASSET_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define PICOPEN_CRAYON_SCREEN_WIDTH {WIDTH}u",
        f"#define PICOPEN_CRAYON_SCREEN_HEIGHT {HEIGHT}u",
        f"#define PICOPEN_CRAYON_SCREEN_COLORS {COLORS}u",
        f"#define PICOPEN_CRAYON_FOCUS_WIDTH {FOCUS_WIDTH}u",
        f"#define PICOPEN_CRAYON_FOCUS_HEIGHT {FOCUS_HEIGHT}u",
        "",
        f"static const uint32_t picopen_crayon_screen_palette[{COLORS}] = {{",
    ]
    for offset in range(0, COLORS, 8):
        values = ", ".join(f"UINT32_C(0x{value:06X})"
                           for value in palette[offset:offset + 8])
        lines.append(f"    {values},")
    lines.extend([
        "};",
        "",
        f"static const uint8_t picopen_crayon_screen_pixels[{WIDTH * HEIGHT}] = {{",
    ])
    for offset in range(0, len(pixels), 32):
        values = ", ".join(f"{value}u" for value in pixels[offset:offset + 32])
        lines.append(f"    {values},")
    lines.extend([
        "};", "",
        "static const uint32_t picopen_crayon_focus_palette[5] = {",
        "    UINT32_C(0x0E9FB5), UINT32_C(0x20B8CA), UINT32_C(0x50CADA),",
        "    UINT32_C(0x1596AE), UINT32_C(0x75D8E2),",
        "};", "",
        f"static const uint8_t picopen_crayon_focus_pixels[6][{FOCUS_WIDTH * FOCUS_HEIGHT}] = {{",
    ])
    for mask in focus_masks:
        lines.append("    {")
        for offset in range(0, len(mask), 32):
            values = ", ".join(f"{value}u" for value in mask[offset:offset + 32])
            lines.append(f"        {values},")
        lines.append("    },")
    lines.extend([
        "};", "",
        f"static const uint8_t picopen_crayon_selected_pixels[6][{FOCUS_WIDTH * FOCUS_HEIGHT}] = {{",
    ])
    for mask in selected:
        lines.append("    {")
        for offset in range(0, len(mask), 32):
            values = ", ".join(f"{value}u" for value in mask[offset:offset + 32])
            lines.append(f"        {values},")
        lines.append("    },")
    lines.extend(["};", "", "#endif", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
